services:
  - type: web
    name: agenda321
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agenda321_db
          property: connectionString
      - key: EDIT_PASSWORD
        sync: false
    autoDeploy: true

databases:
  - name: agenda321_db
    databaseName: agenda321
    user: agenda321
    plan: free
